/**
 * API Response Types - RFC 9457 Compliant
 *
 * This module provides TypeScript interfaces for standardizing REST API responses
 * following RFC 9457 (Problem Details for HTTP APIs).
 *
 * Responses are never enveloped: a success carries the payload alone, an error
 * carries a problem document alone, and pagination travels in the `Link` and
 * `X-Total-Count` response headers.
 *
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 * @see https://www.rfc-editor.org/rfc/rfc8288.html
 */

// ------------------------------------------------------------------------------
// PAGINATION
// ------------------------------------------------------------------------------

/**
 * Link relations emitted by the API's `Link` header.
 *
 * `self`, `first` and `last` are always present on a paginated response;
 * `prev` and `next` appear only when such a page exists.
 */
export type LinkRel = "self" | "first" | "last" | "prev" | "next";

/**
 * Web Link representation following RFC 8288.
 *
 * One parsed entry of the `Link` response header.
 *
 * @see https://www.rfc-editor.org/rfc/rfc8288.html
 *
 * @example
 * ```json
 * { "href": "/products?limit=20&offset=60", "rel": "next" }
 * ```
 */
export type Link = {
	/**
	 * The link's target URI.
	 *
	 * @example "/products?limit=20&offset=60"
	 */
	href: string;

	/**
	 * The relation type of the link.
	 *
	 * @example "next", "prev", "self"
	 */
	rel?: string;

	/**
	 * Human-readable description of the link.
	 */
	title?: string;

	/**
	 * Media type hint for the target resource.
	 *
	 * @example "application/json"
	 */
	type?: string;

	/**
	 * Additional link attributes.
	 */
	[key: string]: unknown;
};

/**
 * Offset pagination as carried by the response headers of a list endpoint.
 *
 * `total` comes from `X-Total-Count` and counts every row matching the filter,
 * ignoring `limit` and `offset`.
 *
 * @example
 * ```typescript
 * const { total, links } = page;
 * const more = links.next?.href;
 * ```
 */
export type Pagination = {
	/**
	 * Rows matching the filter across all pages.
	 */
	total: number;

	/**
	 * Parsed `Link` header entries, keyed by relation.
	 */
	links: Partial<Record<LinkRel, Link>>;
};

// ------------------------------------------------------------------------------
// API RESPONSE
// ------------------------------------------------------------------------------

/**
 * RFC 9457 Problem Details for HTTP APIs.
 *
 * Standard format for machine-readable error responses in HTTP APIs.
 * Must be served with `Content-Type: application/problem+json`.
 *
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 *
 * @example
 * ```json
 * {
 *   "type": "https://api.example.com/errors/validation-error",
 *   "title": "Validation Error",
 *   "status": 400,
 *   "detail": "The request body contains invalid data",
 *   "instance": "/users/create"
 * }
 * ```
 */
export type ProblemDetails = {
	/**
	 * A URI reference that identifies the problem type.
	 *
	 * When dereferenced, it should provide human-readable documentation.
	 *
	 * @default "about:blank"
	 * @example "https://api.example.com/errors/not-found"
	 */
	type: string;

	/**
	 * A short, human-readable summary of the problem type.
	 *
	 * Should be the same for all occurrences of the same problem type.
	 *
	 * @example "Resource Not Found", "Validation Error"
	 */
	title: string;

	/**
	 * The HTTP status code generated by the origin server for this occurrence of the problem.
	 *
	 * @example 404, 400, 500
	 */
	status: number;

	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 *
	 * Should focus on helping the client correct the problem.
	 *
	 * @example "The user with ID 12345 does not exist"
	 */
	detail?: string;

	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 *
	 * It may or may not yield further information if dereferenced.
	 *
	 * @example "/users/12345/update"
	 */
	instance?: string;

	/**
	 * Additional members to provide more context about the problem.
	 *
	 * Can include application-specific fields like trace IDs, support info, etc.
	 */
	[k: string]: unknown;
};

// ------------------------------------------------------------------------------
// CLIENT
// ------------------------------------------------------------------------------

const base = import.meta.env.VITE_BACKEND_URL ?? "http://localhost:3000";

export class ApiError extends Error {
	readonly problem: ProblemDetails;

	constructor(problem: ProblemDetails) {
		super(problem.detail ?? problem.title);
		this.name = "ApiError";
		this.problem = problem;
	}
}

// the token is passed in, not read from storage, so callers own the session
export type RequestOptions = {
	method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
	body?: unknown;
	token?: string;
};

async function problem(res: Response): Promise<ProblemDetails> {
	const fallback: ProblemDetails = {
		type: "about:blank",
		title: res.statusText || String(res.status),
		status: res.status,
	};

	try {
		// an absent `type` means about:blank; the API never sends one
		return { ...fallback, ...((await res.json()) as ProblemDetails) };
	} catch {
		return fallback;
	}
}

async function request(
	path: string,
	options: RequestOptions,
): Promise<Response> {
	const { method = "GET", body, token } = options;
	const headers: Record<string, string> = {};

	if (token !== undefined) {
		headers["authorization"] = `Bearer ${token}`;
	}

	if (body !== undefined) {
		headers["content-type"] = "application/json";
	}

	const res = await fetch(`${base}${path}`, {
		method,
		headers,
		body: body === undefined ? null : JSON.stringify(body),
	});

	if (!res.ok) {
		throw new ApiError(await problem(res));
	}

	return res;
}

export async function fetchApi<T>(
	path: string,
	options: RequestOptions = {},
): Promise<T> {
	const res = await request(path, options);

	// DELETE /cart/:id_variant is the only 204 the API answers
	return res.status === 204 ? (undefined as T) : ((await res.json()) as T);
}

// one RFC 8288 link-value; the API always quotes rel, so bare rels are unhandled
const linkValue = /<([^>]*)>;\s*rel="([^"]*)"/g;

export function parseLinks(header?: string): Pagination["links"] {
	const links: Pagination["links"] = {};

	for (const [, href, rel] of (header ?? "").matchAll(linkValue)) {
		if (href !== undefined && rel !== undefined) {
			links[rel as LinkRel] = { href, rel };
		}
	}

	return links;
}

// pagination rides in the `Link` and `X-Total-Count` headers, not the body
export async function fetchPage<T>(
	path: string,
	options: RequestOptions = {},
): Promise<Pagination & { items: T[] }> {
	const res = await request(path, options);
	const items = (await res.json()) as T[];

	return {
		items,
		total: Number(res.headers.get("X-Total-Count") ?? items.length),
		links: parseLinks(res.headers.get("Link") ?? undefined),
	};
}
